name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download and Install Visual Studio Build Tools
      run: |
        curl -LO https://aka.ms/vs/17/release/vs_buildtools.exe
        start /wait vs_buildtools.exe --quiet --wait --norestart --nocache ^
          --add "Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools" ^
          --includeRecommended
      shell: cmd

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: |
        msbuild SharpWeb.sln /p:Configuration=Release
