name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Reference Assemblies
      run: |
        nuget install Microsoft.NETFramework.ReferenceAssemblies -Version 1.0.3 -OutputDirectory .

    - name: Restore NuGet Packages
      run: nuget restore SharpWeb.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: msbuild SharpWeb.sln /p:Configuration=Release

    - name: Check Build Output
      run: |
        dir /s /b bin\Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BuildOutput
        path: |
          bin\Release\
          **\bin\Release\*
