name: Build .NET Framework Project with VS2019

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Project with VS2019
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" SharpWeb.sln /p:Configuration=Release

    - name: Archive Build Output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: SharpWeb\bin\Release
