name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install .NET Framework 4.0 Targeting Pack
      run: |
        choco install netfx-4.0-devpack -y
      shell: cmd

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: |
        msbuild SharpWeb.sln /p:Configuration=Release
