name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 使用最新的 Windows Runner
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup MSBuild for VS2019
      run: |
        choco install visualstudio2019-buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --includeRecommended --quiet --norestart" -y
        choco install visualstudio2019-workload-netcoretools -y

    - name: Build Project with VS2019
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" SharpWeb.sln /p:Configuration=Release

    - name: Archive Build Output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: SharpWeb\bin\Release
