name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download .NET Framework Reference Assemblies Package
      run: |
        curl -LO https://www.nuget.org/api/v2/package/Microsoft.NETFramework.ReferenceAssemblies.net40/1.0.3
        mkdir -p SharpWeb/packages/Microsoft.NETFramework.ReferenceAssemblies.net40
        tar -xf Microsoft.NETFramework.ReferenceAssemblies.net40.1.0.3.nupkg -C SharpWeb/packages/Microsoft.NETFramework.ReferenceAssemblies.net40
      shell: bash

    - name: Update MSBuild Reference Paths
      run: |
        echo "<PropertyGroup>" > SharpWeb/Directory.Build.props
        echo "  <AdditionalLibPaths>$(pwd)/SharpWeb/packages/Microsoft.NETFramework.ReferenceAssemblies.net40/lib/net40</AdditionalLibPaths>" >> SharpWeb/Directory.Build.props
        echo "</PropertyGroup>" >> SharpWeb/Directory.Build.props
      shell: bash

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: |
        msbuild SharpWeb.sln /p:Configuration=Release /p:ReferencePath=$(pwd)/SharpWeb/packages/Microsoft.NETFramework.ReferenceAssemblies.net40/lib/net40
