name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # 检出代码

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1  # 设置 MSBuild 工具

    - name: Build Project
      run: |
        msbuild SharpWeb.sln /p:Configuration=Release
