name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 可选：安装 MSBuild（如果未正确配置）
    - name: Install MSBuild tools
      run: |
        choco install visualstudio2019-buildtools --include-optional -y
        refreshenv

    # 使用 MSBuild 完整路径构建
    - name: Build with MSBuild
      run: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe MyProject.sln /p:Configuration=Release"

    # 可选：上传构建产物
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          **/bin/Release/
