name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 使用 MSBuild 构建项目
    - name: Build with MSBuild
      run: |
        msbuild MyProject.sln /p:Configuration=Release

    # 可选：存储构建产物
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          **/bin/Release/
