name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install .NET Framework 4.0 Developer Pack
      run: |
        Invoke-WebRequest -Uri https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe -OutFile dotNetFx40_Full_x86_x64.exe
        Start-Process -FilePath .\dotNetFx40_Full_x86_x64.exe -ArgumentList '/quiet', '/norestart' -Wait
      shell: powershell

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: |
        msbuild SharpWeb.sln /p:Configuration=Release
